Q1) Gram-Schmidt Algorithm and QR decomposition

#### i) 
Write a code to generate a random matrix A of size m × n with m > n
and calculate its Frobenius norm, ∥ · ∥F . The entries of A must be of
the form r.dddd (example 5.4316). The inputs are the positive integers
m and n and the output should display the the dimensions and the
calculated norm value.

In [1]:
import numpy as np

In [2]:
def generate_random_matrix(m,n):
    if m > n:
        rand_gen = np.random.default_rng()
        return np.round_(rand_gen.uniform(low=0, high=10, size=(m,n)),4)
    else:
        print("Error: No: of rows are lesser than no: of columns")
        print(f"Given values: rows = {m}, columns = {n}")
        raise ValueError

In [19]:
rand_matrix = generate_random_matrix(7,5)
rand_matrix

array([[0.6423, 1.5334, 0.9052, 8.0401, 9.4426],
       [8.9021, 4.8879, 6.1143, 6.3478, 6.1072],
       [2.7767, 9.1056, 5.9162, 0.5899, 4.4077],
       [5.762 , 0.5416, 5.2428, 8.0668, 6.7741],
       [1.037 , 5.7801, 3.1005, 4.3933, 4.9783],
       [7.6379, 6.4158, 8.9189, 0.3476, 8.2948],
       [5.9115, 7.3383, 7.1538, 4.7171, 5.0529]])

In [4]:
def frobenius_norm(matrix):
    m,n = matrix.shape
    square_sum = 0
    for i in range(m):
        for j in range(n):
            square_sum += matrix[i][j]**2

    return round(np.sqrt(square_sum),4)

In [5]:
frobenius_norm(rand_matrix)

30.9298

In [6]:
def main_Q1_i():
    try:
        print("Condition: No: of rows should be greater than no: of columns")
        m = int(input("Enter no: of rows:"))
        n = int(input("Enter no: of columns:"))

        # Generate random matrix
        rand_matrix = generate_random_matrix(m,n)
        print(f"Dimensions of the generated matrix: {rand_matrix.shape}")

        # Calculate frobenius norm
        f_norm = frobenius_norm(rand_matrix)
        print("Frobenius norm: ", f_norm)
    except ValueError:
        print("Invalid Input !!!")

In [7]:
main_Q1_i()

Condition: No: of rows should be greater than no: of columns
Dimensions of the generated matrix: (7, 5)
Frobenius norm:  35.3884


#### ii) 
Write a code to decide if Gram-Schmidt Algorithm can be applied to
columns of a given matrix A through calculation of rank. The code
should print appropriate messages indicating whether Gram-Schmidt is
applicable on columns of the matrix or not.

In [6]:
def gauss_ellimination(_A,pivot_enable=True):
    A = _A.copy()
    rows , cols = A.shape
    add_count = 0
    mul_count = 0
    div_count = 0

    ## Forward ellimination process -------------------
    # Do below for each row    
    for row in range(rows):
        # Break if current row index is greater than total columns
        if row >= cols:
            break
        # Partial pivotting (if enabled)
        if pivot_enable:
            # Current pivot value
            max_pivot = abs(A[row][row])
            max_pivot_index = row
            # Iterate through pivot column to find the maximum pivot value
            for i in range(row+1,rows):
                if max_pivot < abs(A[i][row]):
                    max_pivot = abs(A[i][row])
                    max_pivot_index = i
            
            # Do partial pivotting
            if row < max_pivot_index:
                A[row],A[max_pivot_index] = A[max_pivot_index],A[row]
            
        else:
            if A[row][row] == 0:
                print("Pivot value is zero. Please enable partial pivotting to do the calculations...")
                return 0

        ## Apply Row transformation for all the rows below current row
        pivot_element = A[row][row]
        for row2 in range(row+1, rows):
            # Interested element: The element that we set to zero
            interested_element = A[row2][row]

            # Check if interested element if zero and skip
            if interested_element == 0:
                continue

            # Calculate the row multiple value
            row_multiple = interested_element/pivot_element
            div_count += 1
            # Update the interested element to zero
            A[row2][row] = 0

            # Iterated through other columns to update the rest of the values in row
            for col in range(row+1, cols):
                tmp = A[row2][col] - row_multiple*A[row][col]
                A[row2][col]= tmp
                mul_count += 1
                add_count += 1
    ## End of Forward ellimination process -------------------
        
    return A

In [7]:
ref_A = gauss_ellimination(rand_matrix)
ref_A

array([[ 9.0927    ,  9.4395    ,  9.4211    ,  3.6637    ,  4.6636    ],
       [ 0.        , -7.94326452, -9.14374391, -2.32104645, -0.89019518],
       [ 0.        ,  0.        , -7.16202592, -0.71420952,  4.86972152],
       [ 0.        ,  0.        ,  0.        , -1.94551182,  0.58940266],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [8]:
def get_rank(_A):
    A = _A.copy()
    A = gauss_ellimination(A)
    rows, cols = A.shape
    rank = min(rows, cols)
    for row in range(rows):
        # Break if current row index is greater than total columns
        if row >= cols:
            break
        # Deduct no of zero rows from rank
        if sum(A[row]) == 0:
            rank -= 1
    return rank    

In [9]:
get_rank(rand_matrix)

4

In [10]:
def is_gram_schmidt_applicable(matrix):
    rank = get_rank(matrix)
    rows,cols = matrix.shape
    print(f"Rank = {rank}, Columns = {cols}")
    # Check if no: columns equal to the rank
    if rank == cols:
        print("Columns of the marix are Linearly Independant")
        print("Gram-Schmidt Algorithm can be applied")
        return True
    else:
        print("Columns of the marix are Linearly dependant")
        print("Gram-Schmidt Algorithm cannot be applied")
        return False


In [20]:
is_gram_schmidt_applicable(rand_matrix)

Rank = 5, Columns = 5
Columns of the marix are Linearly Independant
Gram-Schmidt Algorithm can be applied


True

#### iii) 
Write a code to generate the orthogonal matrix Q from a matrix A
by performing the Gram-Schmidt orthogonalization method. Ensure
that A has linearly independent columns by checking the rank. Keep
generating A until the linear independence is obtained.

In [12]:
def _dot_product(a,b):
    # Check for compatibility
    if a.shape != b.shape:
        print("Given vectors have different dimensions. Hence dot product not applicable")
        return None
    
    r = len(a)
    sum = 0
    for i in range(r):
        sum += a[i]*b[i]

    return round(sum, 4)

In [13]:
def generate_orthogonal_matrix(matrix):
    # Check if Gram-Schmidt Algorithm can be applied to columns of the given matrix
    # ie: Columns are LI
    if not is_gram_schmidt_applicable(matrix):
        return None
    
    rows, cols = matrix.shape
    # Initialize orthogonal_matrix
    Q = np.zeros((rows, cols))
    # print(matrix)
    # Apply Gram-Schmidt orthogonalization on each column vector
    for i in range(cols):
        # ith column of input matrix
        x = matrix[:,i].copy()
        # print(x)

        # Calculate ith column of Q
        v = x.copy()
        for j in range(i-1, -1, -1):
            # jth column of Q
            v_j = Q[:,j].copy()

            x_dot_v = _dot_product(x,v_j)
            v_dot_v = _dot_product(v_j,v_j)
            
            v -= (x_dot_v/v_dot_v)*v_j
        
        # Normalize v
        v = v/np.sqrt(_dot_product(v,v))

        # Update ith column in Q
        Q[:,i] = np.round_(v, 4)
        
    return Q

In [16]:
generate_orthogonal_matrix(rand_matrix)

Rank = 4, Columns = 5
Columns of the marix are Linearly dependant
Gram-Schmidt Algorithm cannot be applied


In [17]:
def main_Q1_iii():
    try:
        A = generate_random_matrix(7,5)
        # Keep generating A until the linear independence is obtained.
        while not is_gram_schmidt_applicable(A):
            A = generate_random_matrix(7,5)
        
        Q = generate_orthogonal_matrix(A)
        print("A: \n", A)
        print("Orthogonal matrix Q: \n", Q)

    except Exception as e:
        print(e)

In [18]:
main_Q1_iii()

Rank = 4, Columns = 5
Columns of the marix are Linearly dependant
Gram-Schmidt Algorithm cannot be applied
Rank = 5, Columns = 5
Columns of the marix are Linearly Independant
Gram-Schmidt Algorithm can be applied
Rank = 5, Columns = 5
Columns of the marix are Linearly Independant
Gram-Schmidt Algorithm can be applied
A: 
 [[ 8.5419      2.65166667 -4.81908365  1.58279229 -0.60255141]
 [ 8.7775     -0.79304545 -2.48019082 -0.53001549 -0.02286998]
 [ 5.889      -2.91044848  6.31665691 -1.88894196 -1.07871874]
 [ 6.2589      3.00803333  3.84651058 -4.2489002   1.07842197]
 [ 6.0485     -4.33980606 -1.74497858  1.9629225   0.87199594]
 [ 1.6981      1.93426364  6.05146023  6.35207885  0.62609228]
 [ 5.962       0.44134848 -0.03510594  0.70319287 -0.65351835]]
Orthogonal matrix Q: 
 [[ 0.0286  0.0553 -0.0389  0.0229 -0.1411]
 [ 0.0294 -0.0165 -0.02   -0.0077 -0.0054]
 [ 0.0197 -0.0607  0.051  -0.0273 -0.2526]
 [ 0.0209  0.0627  0.0311 -0.0615  0.2526]
 [ 0.0202 -0.0905 -0.0141  0.0284  0.20

#### iv) 
Write a code to create a QR decomposition of the matrix A by utilizing
the code developed in the previous sub-parts of this question. Find the
matrices Q and R and then display the value ∥A − (Q.R)∥F , where
∥ · ∥F is the Frobenius norm. The code should also display the total
number of additions, multiplications and divisions to find the result.

In [14]:
# Perform AxB matrix multiplication
def matrix_multiplication(A,B):
    rA, cA = A.shape
    rB, cB = B.shape
    # Check condition for matrix multiplication
    if cA != rB:
        print("Matrices are not compatible to perform multiplication")
        return None
        
    # Initialize resultant matrix
    C = np.zeros((rA,cB))
    # Multilplication
    for row in range(rA):
        for col in range(cB):
            # Sum of product
            sop = 0
            for i in range(cA):
                sop += A[row,i]*B[i,col]
            C[row,col] = sop

    return C



In [65]:
tmp1 = np.diag((2,2))
tmp2 = np.array([[1,2],[3,4]])
print(f"tmp1: \n {tmp1} \n tmp2: \n {tmp2}")
print(matrix_multiplication(tmp1,tmp2))

tmp1: 
 [[2 0]
 [0 2]] 
 tmp2: 
 [[1 2]
 [3 4]]
[[2. 4.]
 [6. 8.]]


In [15]:
def matrix_transpose(A):
    r, c = A.shape
    # Initialize transpose
    A_transpose = np.zeros((c,r))
    for row in range(r):
        for col in range(c):
            A_transpose[col,row] = A[row,col]

    return A_transpose


In [66]:
matrix_transpose(tmp2)

array([[1., 3.],
       [2., 4.]])

In [21]:
matrix_transpose(rand_matrix)

array([[3.8696, 9.1424, 4.6148, 9.5413, 1.2443, 4.2419, 9.7607],
       [1.9022, 5.0495, 7.4663, 0.1768, 5.8562, 8.676 , 3.5379],
       [0.0149, 9.737 , 7.4578, 6.5199, 8.4375, 9.242 , 3.787 ],
       [5.1302, 8.6242, 7.1714, 9.4123, 1.679 , 8.3484, 3.719 ],
       [7.7315, 1.7377, 0.9818, 5.5296, 6.1969, 3.4161, 9.1469]])

In [16]:
def QR_decomposition(A):
    # Generate Q
    Q = generate_orthogonal_matrix(A)
    # Obtain Q transpose
    Q_transpose = matrix_transpose(Q)
    # Obtain R = Q_transpose x A
    R = matrix_multiplication(Q_transpose,A)

    return Q,R

In [17]:
import traceback
def main_Q1_iv():
    try:
        A = generate_random_matrix(7,5)
        # Keep generating A until the linear independence is obtained.
        while not is_gram_schmidt_applicable(A):
            A = generate_random_matrix(7,5)
        print("A: \n",__name__, A)
        
        # QR Decomposition
        Q, R = QR_decomposition(A)
        print("A: \n",A)
        print("Q: \n",Q)
        print("R: \n",R)

        # QR muliplication
        QR = matrix_multiplication(Q,R)
        print("A: \n",A)
        print("Q: \n",Q)
        print("R: \n",R)
        print("QR: \n",QR)

        # value of ∥A − (Q.R)∥F
        print("A-QR: \n",A-QR)
        print("∥A-(Q.R)∥F = ",frobenius_norm(A-QR))


    except Exception as e:
        traceback.print_exc()
        print(e)

In [18]:
main_Q1_iv()

Rank = 4, Columns = 5
Columns of the marix are Linearly dependant
Gram-Schmidt Algorithm cannot be applied
Rank = 5, Columns = 5
Columns of the marix are Linearly Independant
Gram-Schmidt Algorithm can be applied
A: 
 __main__ [[9.     3.1056 7.3745 7.2823 5.2874]
 [1.6211 8.8058 7.2107 4.9337 3.4344]
 [7.1355 6.2748 2.1972 2.8808 1.4069]
 [0.0851 3.5417 7.8682 0.338  4.1927]
 [7.1991 9.0688 1.9857 8.873  2.1186]
 [8.8316 7.6834 1.0007 8.8622 4.3197]
 [3.2754 1.1262 5.0378 1.7104 2.5548]]
Rank = 5, Columns = 5
Columns of the marix are Linearly Independant
Gram-Schmidt Algorithm can be applied
A: 
 [[9.     3.1056 7.3745 7.2823 5.2874]
 [1.6211 8.8058 7.2107 4.9337 3.4344]
 [7.1355 6.2748 2.1972 2.8808 1.4069]
 [0.0851 3.5417 7.8682 0.338  4.1927]
 [7.1991 9.0688 1.9857 8.873  2.1186]
 [8.8316 7.6834 1.0007 8.8622 4.3197]
 [3.2754 1.1262 5.0378 1.7104 2.5548]]
Q: 
 [[ 0.5426 -0.4246  0.4836  0.2857 -0.1557]
 [ 0.0977  0.7521  0.2473  0.1589 -0.1832]
 [ 0.4302  0.0464 -0.1426 -0.8551 -0.